<?php

return [
    'sistem-manajemen-sekolah' => [
        'slug' => 'sistem-manajemen-sekolah',
        'title' => 'Sistem Manajemen Sekolah',
        'year' => 2024,
        'category' => 'Web Application',
        'tagline' => 'Aplikasi manajemen data akademik',
        'description' => 'Aplikasi berbasis web untuk mengelola data absensi dan nilai siswa secara efisien sebagai proyek akhir semester. Fitur utama meliputi manajemen siswa, jadwal pelajaran, dan laporan nilai.',
        'image' => '/images/project_school_management.png',
        'tech' => ['Laravel', 'MySQL', 'Bootstrap'],
        'details' => 'Proyek ini dikembangkan sebagai tugas akhir semester untuk memenuhi kebutuhan administrasi sekolah. Sistem ini mencakup modul data siswa, absensi harian, pengelolaan jadwal pelajaran, dan rekapitulasi nilai akhir. Dibangun menggunakan Laravel untuk backend dan Bootstrap untuk antarmuka yang responsif.',
        'features' => [
            'Manajemen data siswa (CRUD)',
            'Sistem absensi harian',
            'Jadwal pelajaran otomatis',
            'Rekapitulasi nilai akhir',
            'Export laporan dalam format PDF',
        ],
        'link' => '#',
        'gallery' => [
            '/images/project_school_management.png',
            '/images/project_ecommerce.png',
        ],
    ],
    'e-commerce-sederhana' => [
        'slug' => 'e-commerce-sederhana',
        'title' => 'E-Commerce Sederhana',
        'year' => 2024,
        'category' => 'Frontend Development',
        'tagline' => 'Toko online responsif',
        'description' => 'Eksplorasi mandiri dalam membangun antarmuka toko online yang responsif dan interaktif untuk melatih pemahaman frontend. Termasuk fitur keranjang belanja dan validasi form.',
        'image' => '/images/project_ecommerce.png',
        'tech' => ['HTML', 'CSS', 'JavaScript'],
        'details' => 'Proyek eksplorasi mandiri untuk memperdalam pemahaman tentang pengembangan frontend. Dibangun dari nol menggunakan HTML5, CSS3, dan JavaScript vanilla. Mencakup halaman produk, keranjang belanja interaktif, serta validasi form checkout.',
        'features' => [
            'Katalog produk dengan filtering',
            'Keranjang belanja real-time',
            'Validasi form checkout',
            'Desain responsif mobile-first',
            'Interaksi pengguna yang halus',
        ],
        'link' => '#',
        'gallery' => [
            '/images/project_ecommerce.png',
            '/images/project_school_management.png',
        ],
    ],
    'portfolio-website' => [
        'slug' => 'portfolio-website',
        'title' => 'Portfolio Website',
        'year' => 2025,
        'category' => 'Web Development',
        'tagline' => 'Portfolio interaktif modern',
        'description' => 'Website portfolio interaktif dengan animasi GSAP, custom cursor, dan desain modern menggunakan Laravel + Tailwind CSS.',
        'image' => '',
        'tech' => ['Laravel', 'Tailwind', 'GSAP'],
        'details' => 'Portfolio pribadi yang dibangun dengan Laravel dan Tailwind CSS. Menampilkan proyek-proyek dengan animasi smooth menggunakan GSAP, custom cursor dengan spring physics, dan desain yang bersih dan modern.',
        'features' => [
            'Animasi scroll interaktif',
            'Custom cursor premium',
            'Desain responsif',
            'Proyek gallery dengan carousel',
            'Form kontak terintegrasi',
        ],
        'link' => '#',
        'gallery' => [],
    ],
    'aplikasi-todo-list' => [
        'slug' => 'aplikasi-todo-list',
        'title' => 'Aplikasi Todo List',
        'year' => 2024,
        'category' => 'Web Application',
        'tagline' => 'Manajemen tugas harian',
        'description' => 'Aplikasi manajemen tugas berbasis web dengan fitur CRUD, filter status, dan penyimpanan data menggunakan LocalStorage.',
        'image' => '',
        'tech' => ['JavaScript', 'CSS', 'HTML'],
        'details' => 'Aplikasi todo list sederhana dengan fungsionalitas CRUD lengkap. Data disimpan di LocalStorage browser sehingga tetap tersedia meskipun halaman di-refresh. Dilengkapi filter berdasarkan status tugas.',
        'features' => [
            'Tambah, edit, hapus tugas',
            'Filter berdasarkan status',
            'Penyimpanan LocalStorage',
            'Desain minimal dan bersih',
            'Responsif di semua perangkat',
        ],
        'link' => '#',
        'gallery' => [],
    ],
    'sistem-perpustakaan' => [
        'slug' => 'sistem-perpustakaan',
        'title' => 'Sistem Perpustakaan',
        'year' => 2024,
        'category' => 'Web Application',
        'tagline' => 'Manajemen perpustakaan digital',
        'description' => 'Sistem manajemen perpustakaan digital untuk mengelola data buku, anggota, dan transaksi peminjaman.',
        'image' => '',
        'tech' => ['PHP', 'MySQL', 'Bootstrap'],
        'details' => 'Sistem informasi perpustakaan berbasis web yang dibangun dengan PHP dan MySQL. Mencakup manajemen koleksi buku, data anggota, serta transaksi peminjaman dan pengembalian.',
        'features' => [
            'Manajemen koleksi buku',
            'Pendaftaran anggota',
            'Transaksi peminjaman',
            'Riwayat pengembalian',
            'Pencarian buku',
        ],
        'link' => '#',
        'gallery' => [],
    ],
    'company-landing-page' => [
        'slug' => 'company-landing-page',
        'title' => 'Company Landing Page',
        'year' => 2025,
        'category' => 'Frontend Development',
        'tagline' => 'Landing page perusahaan startup',
        'description' => 'Landing page modern untuk perusahaan startup dengan animasi scroll, hero section interaktif, dan desain responsif.',
        'image' => '',
        'tech' => ['HTML', 'Tailwind', 'JavaScript'],
        'details' => 'Landing page profesional untuk perusahaan startup teknologi. Dibangun dengan pendekatan mobile-first menggunakan Tailwind CSS. Menampilkan hero section interaktif, animasi scroll yang halus, dan bagian layanan yang informatif.',
        'features' => [
            'Hero section interaktif',
            'Scroll-triggered animations',
            'Testimonial slider',
            'Pricing section',
            'Form kontak',
        ],
        'link' => '#',
        'gallery' => [],
    ],
];
